### ISSUE TITLE
Module not found: Error: Can't resolve './MockStorage' in '[...]/vuex-persist/dist

### ISSUE THREAD

**Issue by Brian-McBride** [championswimmer/vuex-persist#12]
Just tried to use your plugin (thanks for the development by the way.) However, I did get this error.

**Comment by Tronix117** [comment]
Same here :)

**Comment by CmdrShepardsPie** [comment]
Same, seems to be a problem introduced in 0.5.0, it still works in 0.4.0.

**Comment by RichiCoder1** [comment]
Looks like somehow the dist js got unbundled in this commit: 5066a6c3690bef4663770261976d7febd5304814

**Comment by davi5e** [comment]
**+1**

ERROR in ./node_modules/vuex-persist/dist/index.js
Module not found: Error: Can't resolve './MockStorage' in '<PATH>/node_modules/vuex-persist/dist'
 @ ./node_modules/vuex-persist/dist/index.js 7:20-44
 @ ./resources/assets/js/store.js
 @ ./resources/assets/js/main.js
 @ multi ./resources/assets/js/main.js ./resources/assets/sass/main.scss ./resources/assets/stylus/vuetify.styl

ERROR in ./node_modules/vuex-persist/dist/index.js
Module not found: Error: Can't resolve './SimplePromiseQueue' in '<PATH>/node_modules/vuex-persist/dist'
 @ ./node_modules/vuex-persist/dist/index.js 9:27-58
 @ ./resources/assets/js/store.js
 @ ./resources/assets/js/main.js
 @ multi ./resources/assets/js/main.js ./resources/assets/sass/main.scss ./resources/assets/stylus/vuetify.styl

**Comment by pomeisl** [comment]
When i tried to use 0.5.0, then i met with this:

ERROR in ./node_modules/vuex-persist/dist/index.js
Module not found: Error: Can't resolve './MockStorage' in 'C:\WorkspaceSTS\vue-lessons\vue-pwa-feri-03\node_modules\vuex-persist\dist'
 @ ./node_modules/vuex-persist/dist/index.js 7:20-44
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
ERROR in ./node_modules/vuex-persist/dist/index.js
Module not found: Error: Can't resolve './SimplePromiseQueue' in 'C:\WorkspaceSTS\vue-lessons\vue-pwa-feri-03\node_modules\vuex-persist\dist'
 @ ./node_modules/vuex-persist/dist/index.js 9:27-58
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by jotafurtado** [comment]
Same here! Works in 0.4.

**Comment by championswimmer** [comment]
Should be solved in 0.6.0

**Comment by shannonsands** [comment]
Still getting this issue on latest build- 
Unexpected token: name (MockStorage) [./~/vuex-persist/dist/esm/index.js:6,0]

Using a vue-cli generated project.

**Comment by championswimmer** [comment]
Please use 0.4 meanwhile. Will fix this soon
